#This is a workflow for hello friends.
name: Hello friends
#run on a trigger
  on:
    push:
      branches: main
  jobs:
    greet:
      runs on: ubuntu-latest
      step:
        -name: say Hello friends
         run: echo "Hello friends"
        -name: ask How are you
         run: echo"How are you?"
